// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Author struct {
	ID             int64     `json:"id"`
	User           string    `json:"user"`
	AuthorType     string    `json:"author_type"`
	AuthorIsActive bool      `json:"author_is_active"`
	CreatedAt      time.Time `json:"created_at"`
}

type Course struct {
	ID             int64     `json:"id"`
	Title          string    `json:"title"`
	Subtitle       string    `json:"subtitle"`
	Language       string    `json:"language"`
	Amount         string    `json:"amount"`
	LearningList   string    `json:"learning_list"`
	CourseIncludes string    `json:"course_includes"`
	Content        string    `json:"content"`
	Requirements   string    `json:"requirements"`
	Description    string    `json:"description"`
	TargetStudents string    `json:"target_students"`
	Duration       string    `json:"duration"`
	AuthorID       string    `json:"author_id"`
	CreatedAt      time.Time `json:"created_at"`
}

type Enrollment struct {
	ID                 int64     `json:"id"`
	Student            string    `json:"student"`
	EnrollementName    string    `json:"enrollement_name"`
	EnrollmentIsActive bool      `json:"enrollment_is_active"`
	Duration           string    `json:"duration"`
	CreatedAt          time.Time `json:"created_at"`
}

type EnrollmentCourse struct {
	ID          int64     `json:"id"`
	StudentName string    `json:"student_name"`
	CourseID    int64     `json:"course_id"`
	ExpiresAt   time.Time `json:"expires_at"`
	CreatedAt   time.Time `json:"created_at"`
}

type EnrollmentEvent struct {
	ID           int64     `json:"id"`
	EnrollmentID int64     `json:"enrollment_id"`
	EventID      int64     `json:"event_id"`
	CreatedAt    time.Time `json:"created_at"`
}

type EnrollmentPayment struct {
	ID           int64     `json:"id"`
	Name         string    `json:"name"`
	Amount       int64     `json:"amount"`
	EnrollmentID int64     `json:"enrollment_id"`
	PaymentDate  time.Time `json:"payment_date"`
	CreatedAt    time.Time `json:"created_at"`
}

type Event struct {
	ID             int64     `json:"id"`
	Speaker        string    `json:"speaker"`
	EventName      string    `json:"event_name"`
	EventType      string    `json:"event_type"`
	EventIsActive  bool      `json:"event_is_active"`
	EventStartDate time.Time `json:"event_start_date"`
	EventEndDate   time.Time `json:"event_end_date"`
	CreatedAt      time.Time `json:"created_at"`
}

type Rating struct {
	ID              int64     `json:"id"`
	Reviewer        string    `json:"reviewer"`
	EnrollmmentID   int64     `json:"enrollmment_id"`
	EnrollmentCount int32     `json:"enrollment_count"`
	EnrollmentType  string    `json:"enrollment_type"`
	Ratings         int64     `json:"ratings"`
	ReviewText      string    `json:"review_text"`
	CreatedAt       time.Time `json:"created_at"`
}

type Session struct {
	ID           uuid.UUID `json:"id"`
	Username     string    `json:"username"`
	RefreshToken string    `json:"refresh_token"`
	UserAgent    string    `json:"user_agent"`
	ClientIp     string    `json:"client_ip"`
	IsBlocked    bool      `json:"is_blocked"`
	ExpiresAt    time.Time `json:"expires_at"`
	CreatedAt    time.Time `json:"created_at"`
}

type Speaker struct {
	ID        int64     `json:"id"`
	User      string    `json:"user"`
	CreatedAt time.Time `json:"created_at"`
}

type Student struct {
	ID              int64     `json:"id"`
	User            string    `json:"user"`
	StudentIsActive bool      `json:"student_is_active"`
	CreatedAt       time.Time `json:"created_at"`
}

type User struct {
	Username          string    `json:"username"`
	HashedPassword    string    `json:"hashed_password"`
	FirstName         string    `json:"first_name"`
	LastName          string    `json:"last_name"`
	Email             string    `json:"email"`
	Address           string    `json:"address"`
	Address2          string    `json:"address2"`
	City              string    `json:"city"`
	Country           string    `json:"country"`
	IsEmailVerified   bool      `json:"is_email_verified"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
}

type VerifyEmail struct {
	ID         int64     `json:"id"`
	Username   string    `json:"username"`
	Email      string    `json:"email"`
	SecretCode string    `json:"secret_code"`
	IsUsed     bool      `json:"is_used"`
	CreatedAt  time.Time `json:"created_at"`
	ExpiredAt  time.Time `json:"expired_at"`
}
